/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./../src/components/AppLogo/AppLogo.vue')['default']
    BackTop: typeof import('./../src/components/BackTop/BackTop.vue')['default']
    BlankView: typeof import('./../src/components/BlankView/BlankView.vue')['default']
    'IEmojione:memo': typeof import('~icons/emojione/memo')['default']
    'IEmojioneV1:flagForChina': typeof import('~icons/emojione-v1/flag-for-china')['default']
    IFaSolidDiceFive: typeof import('~icons/fa-solid/dice-five')['default']
    'IFluent:emoji32Filled': typeof import('~icons/fluent/emoji32-filled')['default']
    'IHeroiconsOutline:menuAlt2': typeof import('~icons/heroicons-outline/menu-alt2')['default']
    IHeroiconsOutlineMenuAlt2: typeof import('~icons/heroicons-outline/menu-alt2')['default']
    IIconGiftbox: typeof import('~icons/icon/giftbox')['default']
    IIconIc_right: typeof import('~icons/icon/ic_right')['default']
    IIconLogo: typeof import('~icons/icon/logo')['default']
    IIcTwotone24mp: typeof import('~icons/ic/twotone24mp')['default']
    'IMdi:cactus': typeof import('~icons/mdi/cactus')['default']
    'IMdi:lightFloodDown': typeof import('~icons/mdi/light-flood-down')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IMdiDiceD12: typeof import('~icons/mdi/dice-d12')['default']
    IMdiLightAlarm: typeof import('~icons/mdi-light/alarm')['default']
    INotoV1FlagForFlagJapan: typeof import('~icons/noto-v1/flag-for-flag-japan')['default']
    IRiApps2Line: typeof import('~icons/ri/apps2-line')['default']
    ITwemoji1stPlaceMedal: typeof import('~icons/twemoji/1st-place-medal')['default']
    ITwemojiFlagAruba: typeof import('~icons/twemoji/flag-aruba')['default']
    ITwemojiFlagChina: typeof import('~icons/twemoji/flag-china')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/SvgIcon/SvgIcon.vue')['default']
  }
}
