/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./../src/components/AppLogo/AppLogo.vue')['default']
    BackTop: typeof import('./../src/components/BackTop/BackTop.vue')['default']
    BlankView: typeof import('./../src/components/BlankView/BlankView.vue')['default']
    ICustomLogo: typeof import('~icons/custom/logo')['default']
    IElEdit: typeof import('~icons/el/edit')['default']
    IInlineAsync: typeof import('~icons/inline/async')['default']
    IInlineFoo: typeof import('~icons/inline/foo')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/SvgIcon/SvgIcon.vue')['default']
  }
}
