/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./../components/AppLogo/AppLogo.vue')['default']
    BackTop: typeof import('./../components/BackTop/BackTop.vue')['default']
    BlankView: typeof import('./../components/BlankView/BlankView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
